name: docker-push

on:
  workflow_dispatch:

env:
 imageName: hueadm

jobs:

  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set Docker Labels
      id: prep
      run: |
        echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        echo ::set-output name=labelref::$(date +%s)
        echo ::set-output name=nodePackageVer::$(npm view hueadm dist-tags.latest)
        
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ GITHUB.ACTOR }}
        password: ${{ secrets.GHCRIO_PAT }}
        logout: true
      
    - name: Build an Publish Image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          mmuffins/hueadm:latest
          mmuffins/hueadm:${{ steps.prep.outputs.nodePackageVer }}
          ghcr.io/mmuffins/hueadm:latest
          ghcr.io/mmuffins/hueadm:${{ steps.prep.outputs.nodePackageVer }}
        context: ${{ GITHUB.WORKSPACE }}
        file: docker/Dockerfile
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
        labels: |
          org.opencontainers.image.title=${{ github.event.repository.name }}
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.version=${{ steps.prep.outputs.nodePackageVer }}
          org.opencontainers.image.licenses='MIT'